### ISSUE TITLE
Handling join

### ISSUE THREAD

**Issue by prashantham** [dockyard/inquisitor#12]
Hi,
    If i wanted to join with another table and search on its fields then i would include them in "build_post_query" function?

**Comment by bcardarella** [comment]
Yes, that is correct.

**Comment by acrolink** [comment]
An example will be highly appreciated. Thank you.

**Comment by acrolink** [comment]
Here's how I have managed to do it, correct me if there is a better solution:

```
  def build_query(query, "user_id", user_id, _conn) when user_id != "" do
    from p in query,
      join: u in assoc(p, :user),
      where: u.id == ^user_id
  end
```
