### ISSUE TITLE
Feature request: define "base" query 

### ISSUE THREAD

**Issue by mike-north** [dockyard/inquisitor#15]
A useful addition to this library would be the ability to define a "base query" to use in the absence of anything interesting in "params". A common use case might be soft delete, where a non-null `deleted_at` field is used in order to indicate records that shouldn't be returned/rendered in a typical `:index` action.

In this case, we would want to start with 

```ex
from r in Record, where: is_nil(r.deleted_at)
```
instead of the current "base"

```ex
from r in Record
```

To make things more interesting, this can sometimes vary depending on external factors (i.e., user is authenticated, and has role XYZ, so they can now see deleted records).

**Comment by bcardarella** [comment]
I've gone back and forth on what the proper implementation of this should be. For the time being I'm settling on suggesting people modify `conn.params` with a `plug`:

```elixir
defmodule MyApp.PostController do
  use MayApp.Web, :controller
  use Inquisitor

  plug :default_params when action in [:index]

  defp default_params(conn) do
    params = Map.put_new(conn.params, "filter", %{"foo" => "bar"})
    %{conn | params: params}
  end
end
```

Then let Inquisitor handle the params as it normally would. I'm experimenting with this on dockyard.com, will update docs soon.
