### ISSUE TITLE
Limit handler?

### ISSUE THREAD

**Issue by bcardarella** [dockyard/inquisitor#2]
I'm debating adding a limit handler.

**Comment by codyjroberts** [comment]
Seems like a common use case so I gave it a shot.

**Comment by codyjroberts** [comment]
@bcardarella I see that the build failed on TravisCI.  I think it's because the PR was closed and merged before the build finished.  Tests passed on my end, but let me know if any issues ensue.

**Comment by bcardarella** [comment]
Master seems to be green so I think we're good
