### ISSUE TITLE
warning: module attribute @whitelist was set but never used

### ISSUE THREAD

**Issue by blatyo** [dockyard/inquisitor#24]
## Version
Inquisitor 0.5.0
Elixir 1.4.1

## Test Case
Specify a `@whitelist` attribute

## Steps to reproduce
`mix compile`

## Expected Behavior
No warning emitted

## Actual Behavior
Warning emitted

**Comment by bcardarella** [comment]
How are you using it? `@whitelist` is only recommended as use for a guard in an override function you are supposed to write yourself. It isn't consumed in the library code otherwise.

**Comment by blatyo** [comment]
Sorry, I misunderstood the docs. I thought, `@whitelist` was used by the library to define a default handler. I just upgraded from `0.2.0` where the library did define a default based on whitelist.

**Comment by bcardarella** [comment]
gotcha, check out the migration guide: https://github.com/DockYard/inquisitor/blob/master/MIGRATION_GUIDE.md
